const { JSDOM } = require("jsdom");
const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost/" });
global.window=dom.window; global.document=dom.window.document; global.navigator=dom.window.navigator; global.localStorage=dom.window.localStorage;
global.Element=dom.window.Element; global.HTMLElement=dom.window.HTMLElement;
window.HTMLElement.prototype.scrollIntoView=function(){};
localStorage.setItem("teamsheet:v1", JSON.stringify({seenOnboarding:true,coins:50,lives:2,livesAt:Date.now(),streak:4,best:6,collected:31,played:9,dayCurrent:0,dayResults:[],dayFinished:false,lastDay:null,levelReached:1,clearedLevels:[0],matchesSolved:[]}));
const React=require("react"); const {createRoot}=require("react-dom/client"); const {act}=React;
console.log("T0 requiring bundle…");
const Page=require("./page.bundle.cjs").default;
console.log("T1 bundle loaded");
const click=async(b)=>act(async()=>{b.dispatchEvent(new window.MouseEvent("click",{bubbles:true}));});
const find=(re)=>[...document.querySelectorAll("button")].find(b=>re.test(b.textContent));
const type=async(v)=>{const i=document.querySelector("input");const set=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value").set;await act(async()=>{set.call(i,v);i.dispatchEvent(new window.Event("input",{bubbles:true}));});};
(async()=>{ try{
  const root=createRoot(document.getElementById("root"));
  await act(async()=>{root.render(React.createElement(Page));});
  console.log("T2 rendered");
  const later=find(/LATER/); if(later) await click(later);
  console.log("T3 popup done");
  await click(find(/Levels/)); console.log("T4 levels tab");
  await click(find(/▶/)); console.log("T5 level popup");
  await click(find(/PLAY →/)); console.log("T6 match mounted");
  await type("Curtis Jones"); console.log("T7 typed");
  const sg=document.querySelector(".sugg button");
  console.log("T8 suggestion:", sg && sg.textContent.trim());
  await click(sg); console.log("T9 wrong guess 1 done, lives text:", /❤️ ?\d|(\d) left/.exec(document.body.textContent)?.[0]);
  await type("James Milner"); const sg2=document.querySelector(".sugg button");
  await click(sg2); console.log("T10 wrong guess 2 done");
  if (!/OUT OF LIVES/i.test(document.body.textContent)) throw new Error("gate missing");
  console.log("GATE PASS — wrong guesses (incl. Curtis Jones) drain to a working gate");
  process.exit(0);
}catch(e){console.log("FAIL:", (e.stack||e.message||"").split("\n").slice(0,8).join("\n")); process.exit(1);}})();
