// pipeline/emit.mjs
// Stage 3: emit the app's generated-data module and merged level structure.
// Generated puzzles (real FPL data, 2016-now) + curated classics (hand-verified
// 1992-2016) = the app's full bank. Generated player IDs are "g<code>" so they
// can never collide with curated keys.

import fs from "fs";

const { bank, players } = JSON.parse(fs.readFileSync("bank_generated.json", "utf8"));
const POSMAP = { GK: "GK", DEF: "DF", MID: "MF", FWD: "FW" };
const fold = (s) => s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
  .replace(/\u00f8/g, "o").replace(/\u0111/g, "d").replace(/\u0142/g, "l");
const TMPOS_ABBR = { "Goalkeeper":"GK","Centre-Back":"CB","Left-Back":"LB","Right-Back":"RB",
  "Defensive Midfield":"CDM","Central Midfield":"CM","Attacking Midfield":"CAM",
  "Left Midfield":"LM","Right Midfield":"RM","Left Winger":"LW","Right Winger":"RW",
  "Centre-Forward":"ST","Second Striker":"SS","Sweeper":"CB" };
const TMPOS = {};
for (const l of fs.readFileSync("raw/tm_transfers_pl.csv", "utf8").split("\n").slice(1)) {
  const c = l.split(",");
  if (c[1] && c[3] && TMPOS_ABBR[c[3]]) TMPOS[fold(c[1])] = TMPOS_ABBR[c[3]];
}

// ---- curate: balanced selection from the 180 -----------------------------------
const byDiff = { easy: [], medium: [], hard: [] };
for (const b of bank) byDiff[b.diff].push(b);          // already quality-sorted
const chosen = [
  ...byDiff.easy.slice(0, 15),
  ...byDiff.medium.slice(0, 18),
  ...byDiff.hard.slice(0, 15),
];
console.log(`Curated ${chosen.length} generated puzzles for the app (of ${bank.length})`);

// ---- player entries: everyone appearing in chosen puzzles + search depth -------
const usedIds = new Set();
for (const b of chosen) { usedIds.add(b.answer); b.clues.forEach(c => usedIds.add(c)); }
// add extra well-known players purely for search/guess depth (good wrong guesses)
const extras = Object.keys(players)
  .filter(c => !usedIds.has(c) && players[c].minutes >= 9000)
  .sort((a, b) => players[b].minutes - players[a].minutes)
  .slice(0, 150);
const allIds = [...usedIds, ...extras];

function rating(c) {
  // fame-derived prime-ish rating band 70-90 (approximate by construction)
  const p = players[c];
  const pct = Math.min(p.minutes / 18000, 1) * 0.35 + Math.min(p.maxCost / 130, 1) * 0.65;
  return Math.round(70 + pct * 20);
}
function clubsSummary(c) { return Object.keys(players[c].clubs).join(" / "); }

let plines = [];
for (const c of allIds.sort((a, b) => players[a].display.localeCompare(players[b].display))) {
  const p = players[c];
  plines.push(`  g${c}: [${JSON.stringify(p.display)}, ${JSON.stringify(clubsSummary(c))}, ${JSON.stringify(POSMAP[p.mainPos])}, "⚽", ${JSON.stringify(TMPOS[fold(p.display)] || p.mainPos)}, ${rating(c)}],`);
}

let blines = chosen.map(b =>
  `  {clues:[${b.clues.map(c => JSON.stringify("g" + c)).join(",")}],answer:${JSON.stringify("g" + b.answer)},valid:[${JSON.stringify("g" + b.answer)}],diff:${JSON.stringify(b.diff)},sharedClubs:[${b.sharedClubs.map(s => JSON.stringify(s)).join(",")}],era:${JSON.stringify(b.era)}},`
);

const file = `// data/generated.js
// AUTO-GENERATED by the content pipeline (pipeline/) from real FPL season data
// (vaastav/Fantasy-Premier-League, seasons 2016-17..2025-26). Every puzzle is
// verified single-answer against the full ${Object.keys(players).length}-player teammate graph.
// Do not hand-edit; re-run the pipeline instead. Historic (pre-2016) puzzles
// live in data/players.js as the curated classics set. The same pipeline
// ingests the full Transfermarkt dataset in the server phase to extend
// coverage to 1992 (see pipeline/README.md).

export const GEN_PLAYERS = {
${plines.join("\n")}
};

export const GEN_BANK = [
${blines.join("\n")}
];
`;
fs.writeFileSync("generated.js", file);
const mix = {}; chosen.forEach(b => mix[b.diff] = (mix[b.diff] || 0) + 1);
console.log(`Emitted generated.js | players ${plines.length} | puzzles ${blines.length} | mix ${JSON.stringify(mix)}`);
