// pipeline/players_meta.mjs
// DISPLAY_FIX: canonical display names for entries the heuristics mangle
// (full Brazilian/Portuguese legal names, FPL abbreviations).
// PLAYER_FLAGS: nationality flags for generated players — confident entries
// only; anyone absent simply shows no flag (never guessed). The Transfermarkt
// players.csv adapter supersedes this with verified data for everyone.

export const DISPLAY_FIX = {
  "Bernardo Mota Veiga de Carvalho e Silva": "Bernardo Silva",
  "Rodrigo 'Rodri' Hernandez Cascante": "Rodri",
  "Rúben dos Santos Gato Alves Dias": "Rúben Dias",
  "Gabriel dos Santos Magalhães": "Gabriel Magalhães",
  "Joelinton Cássio Apolinário de Lira": "Joelinton",
  "Adama Traoré Diarra": "Adama Traoré",
  "Andreas Hoelgebaum Pereira": "Andreas Pereira",
  "Richarlison de Andrade": "Richarlison",
  "Willian Borges da Silva": "Willian",
  "Cédric Alves Soares": "Cédric Soares",
  "Ricardo Barbosa Pereira": "Ricardo Pereira",
  "Raúl Jiménez Rodríguez": "Raúl Jiménez",
  "De Gea": "David de Gea",
  "Bruno G.": "Bruno Guimarães",
  "Diogo J.": "Diogo Jota",
  "Ederson M.": "Ederson",
  "Doucoure": "Abdoulaye Doucouré",
  "Solanke": "Dominic Solanke",
  "Idrissa Gana": "Idrissa Gueye",
  "Fabianski": "Łukasz Fabiański",
  "Mario Jr.": "Mario Lemina",
  "Petr Cech": "Petr Čech",
  "Hegazi": "Ahmed Hegazi",
  "Pedro Rodríguez Ledesma": "Pedro",
  "Paquetá": "Lucas Paquetá",
};

export const PLAYER_FLAGS = {
  // ---- goalkeepers / defenders / mids / forwards, alphabetical-ish ----
  "Aaron Cresswell":"🏴","Aaron Ramsdale":"🏴","Aaron Wan-Bissaka":"🏴","Adam Lallana":"🏴",
  "Adam Smith":"🏴","Adam Webster":"🏴","Adama Traoré":"🇪🇸","Ainsley Maitland-Niles":"🏴",
  "Alex Iwobi":"🇳🇬","Alex McCarthy":"🏴","Alexandre Lacazette":"🇫🇷","Alexis Mac Allister":"🇦🇷",
  "Alfie Mawson":"🏴","Alisson Becker":"🇧🇷","Alphonse Areola":"🇫🇷","Andreas Pereira":"🇧🇷",
  "Andrew Robertson":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Andros Townsend":"🏴","Angelo Ogbonna":"🇮🇹","Anthony Elanga":"🇸🇪",
  "Anthony Gordon":"🏴","Anthony Martial":"🇫🇷","Antonee Robinson":"🇺🇸","Antonio Rüdiger":"🇩🇪",
  "Ashley Barnes":"🏴","Ashley Westwood":"🏴","Ashley Young":"🏴","Asmir Begović":"🇧🇦",
  "Axel Tuanzebe":"🏴","Aymeric Laporte":"🇪🇸","Ayoze Pérez":"🇪🇸","Ben Chilwell":"🏴",
  "Ben Davies":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","Ben Foster":"🏴","Ben Gibson":"🏴","Ben Godfrey":"🏴",
  "Ben Mee":"🏴","Benjamin White":"🏴","Bernardo Silva":"🇵🇹","Bernd Leno":"🇩🇪",
  "Brennan Johnson":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","Bruno Fernandes":"🇵🇹","Bruno Guimarães":"🇧🇷","Bryan Mbeumo":"🇨🇲",
  "Bukayo Saka":"🏴","Callum Wilson":"🏴","Calum Chambers":"🏴","Cédric Soares":"🇵🇹",
  "César Azpilicueta":"🇪🇸","Charlie Taylor":"🏴","Cheikhou Kouyaté":"🇸🇳","Chris Wood":"🇳🇿",
  "Christian Benteke":"🇧🇪","Christian Eriksen":"🇩🇰","Christian Nørgaard":"🇩🇰","Conor Coady":"🏴",
  "Conor Gallagher":"🏴","Craig Cathcart":"🇬🇧","Craig Dawson":"🏴","Cristian Romero":"🇦🇷",
  "Dan Burn":"🏴","Daniel Amartey":"🇬🇭","Daniel James":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","Danny Ings":"🏴",
  "Danny Rose":"🏴","Danny Welbeck":"🏴","Darren Fletcher":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","David Luiz":"🇧🇷",
  "David Raya":"🇪🇸","David Silva":"🇪🇸","David de Gea":"🇪🇸","Davinson Sánchez":"🇨🇴",
  "Dean Henderson":"🏴","Declan Rice":"🏴","Dejan Kulusevski":"🇸🇪","Dele Alli":"🏴",
  "Demarai Gray":"🏴","Diego Costa":"🇪🇸","Diogo Dalot":"🇵🇹","Diogo Jota":"🇵🇹",
  "Dominic Calvert-Lewin":"🏴","Dominic Solanke":"🏴","Abdoulaye Doucouré":"🇲🇱","Douglas Luiz":"🇧🇷",
  "Dwight McNeil":"🏴","Eberechi Eze":"🏴","Ederson":"🇧🇷","Edouard Mendy":"🇸🇳",
  "Emile Smith Rowe":"🏴","Enzo Fernández":"🇦🇷","Eric Dier":"🏴","Erik Pieters":"🇳🇱",
  "Erling Haaland":"🇳🇴","Ethan Pinnock":"🇯🇲","Etienne Capoue":"🇫🇷","Ezri Konsa":"🏴",
  "Fabian Delph":"🏴","Fabian Schär":"🇨🇭","Łukasz Fabiański":"🇵🇱","Fabinho":"🇧🇷",
  "Federico Fernández":"🇦🇷","Fernandinho":"🇧🇷","Fraser Forster":"🏴","Gabriel Magalhães":"🇧🇷",
  "Gabriel Jesus":"🇧🇷","Gabriel Martinelli":"🇧🇷","Gary Cahill":"🏴","Georginio Wijnaldum":"🇳🇱",
  "Granit Xhaka":"🇨🇭","Guglielmo Vicario":"🇮🇹","Gylfi Sigurdsson":"🇮🇸","Harrison Reed":"🏴",
  "Harry Kane":"🏴","Harry Maguire":"🏴","Harvey Barnes":"🏴","Héctor Bellerín":"🇪🇸",
  "Hugo Bueno":"🇪🇸","Hugo Lloris":"🇫🇷","Ibrahima Konaté":"🇫🇷","Idrissa Gueye":"🇸🇳",
  "Ilkay Gündogan":"🇩🇪","Illan Meslier":"🇫🇷","Ismaïla Sarr":"🇸🇳","Issa Diop":"🇫🇷",
  "Jack Cork":"🏴","Jack Grealish":"🏴","Jack Harrison":"🏴","Jack Stephens":"🏴",
  "Jacob Murphy":"🏴","Jacob Ramsey":"🏴","Jake O'Brien":"🇮🇪","Jamaal Lascelles":"🏴",
  "James Justin":"🏴","James Maddison":"🏴","James McArthur":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","James Milner":"🏴",
  "James Tarkowski":"🏴","James Tomkins":"🏴","James Ward-Prowse":"🏴","Jamie Vardy":"🏴",
  "Jan Bednarek":"🇵🇱","Jan Vertonghen":"🇧🇪","Jarrod Bowen":"🏴","Jay Rodriguez":"🏴",
  "Jeff Hendrick":"🇮🇪","Jefferson Lerma":"🇨🇴","Jeffrey Schlupp":"🇬🇭","Jesse Lingard":"🏴",
  "Joachim Andersen":"🇩🇰","João Moutinho":"🇵🇹","João Palhinha":"🇵🇹","João Pedro":"🇧🇷",
  "Joe Gomez":"🏴","Joe Willock":"🏴","Joel Matip":"🇨🇲","Joël Veltman":"🇳🇱",
  "Joel Ward":"🏴","Joelinton":"🇧🇷","Jóhann Gudmundsson":"🇮🇸","John Lundstram":"🏴",
  "John McGinn":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","John Stones":"🏴","Jonjo Shelvey":"🏴","Jonny Evans":"🇬🇧",
  "Jordan Ayew":"🇬🇭","Jordan Henderson":"🏴","Jordan Pickford":"🏴","Jordon Ibe":"🏴",
  "Jorginho":"🇮🇹","José Sá":"🇵🇹","Josh Brownhill":"🏴","Joshua King":"🇳🇴",
  "Kai Havertz":"🇩🇪","Kalvin Phillips":"🏴","Kasper Schmeichel":"🇩🇰","Kepa Arrizabalaga":"🇪🇸",
  "Kevin De Bruyne":"🇧🇪","Kieran Trippier":"🏴","Kurt Zouma":"🇫🇷","Kyle Walker":"🏴",
  "Kyle Walker-Peters":"🏴","Leander Dendoncker":"🇧🇪","Leandro Trossard":"🇧🇪","Leroy Sané":"🇩🇪",
  "Lesley Ugochukwu":"🇫🇷","Lewis Cook":"🏴","Lewis Dunk":"🏴","Lucas Digne":"🇫🇷",
  "Luka Milivojevic":"🇷🇸","Luke Shaw":"🏴","Manuel Lanzini":"🇦🇷","Marc Albrighton":"🏴",
  "Marc Cucurella":"🇪🇸","Marc Guéhi":"🏴","Marcos Alonso":"🇪🇸","Marcus Rashford":"🏴",
  "Mario Lemina":"🇬🇦","Mark Noble":"🏴","Martin Dúbravka":"🇸🇰","Martin Ødegaard":"🇳🇴",
  "Marvelous Nakamba":"🇿🇼","Mason Holgate":"🏴","Mason Mount":"🏴","Mateo Kovačić":"🇭🇷",
  "Mathew Ryan":"🇦🇺","Mathias Jensen":"🇩🇰","Matt Doherty":"🇮🇪","Matt Ritchie":"🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Matt Targett":"🏴","Matthew Lowton":"🏴","Matty Cash":"🇵🇱","Maximilian Kilman":"🏴",
  "Michael Keane":"🏴","Michail Antonio":"🇯🇲","Miguel Almirón":"🇵🇾","Mohamed Salah":"🇪🇬",
  "Moisés Caicedo":"🇪🇨","Morgan Gibbs-White":"🏴","Mousa Dembélé":"🇧🇪","Moussa Sissoko":"🇫🇷",
  "N'Golo Kanté":"🇫🇷","Nathan Aké":"🇳🇱","Nathan Collins":"🇮🇪","Nathan Redmond":"🏴",
  "Nathaniel Clyne":"🏴","Neal Maupay":"🇫🇷","Neco Williams":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","Nélson Semedo":"🇵🇹",
  "Nemanja Matic":"🇷🇸","Nick Pope":"🏴","Oleksandr Zinchenko":"🇺🇦","Ollie Watkins":"🏴",
  "Oriol Romeu":"🇪🇸","Pablo Fornals":"🇪🇸","Pascal Groß":"🇩🇪","Patrick van Aanholt":"🇳🇱",
  "Paul Pogba":"🇫🇷","Pedro Neto":"🇵🇹","Pedro Porro":"🇪🇸","Petr Čech":"🇨🇿",
  "Phil Foden":"🏴","Philip Billing":"🇩🇰","Philippe Coutinho":"🇧🇷","Pierre-Emerick Aubameyang":"🇬🇦",
  "Pierre-Emile Højbjerg":"🇩🇰","Raheem Sterling":"🏴","Raúl Jiménez":"🇲🇽","Rayan Aït-Nouri":"🇩🇿",
  "Reece James":"🏴","Ricardo Pereira":"🇵🇹","Richarlison":"🇧🇷","Riyad Mahrez":"🇩🇿",
  "Robert Sánchez":"🇪🇸","Roberto Firmino":"🇧🇷","Rodri":"🇪🇸","Romelu Lukaku":"🇧🇪",
  "Ross Barkley":"🏴","Rúben Dias":"🇵🇹","Ruben Loftus-Cheek":"🏴","Rúben Neves":"🇵🇹",
  "Rui Patrício":"🇵🇹","Ryan Bertrand":"🏴","Ryan Fraser":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Ryan Shawcross":"🏴",
  "Sadio Mané":"🇸🇳","Salomón Rondón":"🇻🇪","Sam Johnstone":"🏴","Sander Berge":"🇳🇴",
  "Scott McTominay":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Séamus Coleman":"🇮🇪","Sean Longstaff":"🏴","Serge Aurier":"🇨🇮",
  "Shane Duffy":"🇮🇪","Shkodran Mustafi":"🇩🇪","Solly March":"🏴","Son Heung-min":"🇰🇷",
  "Steve Cook":"🏴","Theo Walcott":"🏴","Thiago Silva":"🇧🇷","Thomas Partey":"🇬🇭",
  "Timothy Castagne":"🇧🇪","Toby Alderweireld":"🇧🇪","Tomáš Souček":"🇨🇿","Trent Alexander-Arnold":"🏴",
  "Troy Deeney":"🏴","Tyrick Mitchell":"🏴","Tyrone Mings":"🏴","Vicente Guaita":"🇪🇸",
  "Victor Lindelöf":"🇸🇪","Virgil van Dijk":"🇳🇱","Vitalii Mykolenko":"🇺🇦","Vitaly Janelt":"🇩🇪",
  "Vladimír Coufal":"🇨🇿","Wayne Hennessey":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","Wilfred Ndidi":"🇳🇬","Wilfried Zaha":"🇨🇮",
  "Will Hughes":"🏴","William Saliba":"🇫🇷","Willian":"🇧🇷","Willy Boly":"🇨🇮",
  "Youri Tielemans":"🇧🇪","Yves Bissouma":"🇲🇱","Erling Haaland":"🇳🇴","Eric Garcia":"🇪🇸",
  "Cole Palmer":"🏴","Cody Gakpo":"🇳🇱","Curtis Jones":"🏴","Alexander Isak":"🇸🇪",
  "Allan Saint-Maximin":"🇫🇷","Anthony Elanga":"🇸🇪","Benoît Badiashile":"🇫🇷","Darwin Núñez":"🇺🇾",
  "Dominik Szoboszlai":"🇭🇺","Elliot Anderson":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Emerson Royal":"🇧🇷","Emiliano Martínez":"🇦🇷",
  "Erik Lamela":"🇦🇷","Ferran Torres":"🇪🇸","Fred":"🇧🇷","Harvey Elliott":"🏴",
  "João Cancelo":"🇵🇹","Jurriën Timber":"🇳🇱","Levi Colwill":"🏴","Lewis Hall":"🏴",
  "Lewis Miley":"🏴","Luis Díaz":"🇨🇴","Malo Gusto":"🇫🇷","Manuel Akanji":"🇨🇭",
  "Mykhailo Mudryk":"🇺🇦","Myles Lewis-Skelly":"🏴","Nathaniel Phillips":"🏴","Nicolas Jackson":"🇸🇳",
  "Noni Madueke":"🏴","Nuno Tavares":"🇵🇹","Rhys Williams":"🏴","Rob Holding":"🏴",
  "Rodrigo Bentancur":"🇺🇾","Ryan Gravenberch":"🇳🇱","Sandro Tonali":"🇮🇹","Scott Carson":"🏴",
  "Sepp Van den Berg":"🇳🇱","Sergio Gómez":"🇪🇸","Sergio Reguilón":"🇪🇸","Sven Botman":"🇳🇱",
  "Tanguy Ndombele":"🇫🇷","Thiago Alcântara":"🇪🇸","Tino Livramento":"🏴","Trézéguet":"🇪🇬",
  "Wataru Endo":"🇯🇵","Terence Kongolo":"🇳🇱",
  "Adam Armstrong":"🏴","Ademola Lookman":"🇳🇬","Ahmed El Mohamady":"🇪🇬","Aleksandar Mitrović":"🇷🇸",
  "Alex Moreno":"🇪🇸","Alexis Sánchez":"🇨🇱","André Gomes":"🇵🇹","André-Frank Anguissa":"🇨🇲",
  "Antoine Semenyo":"🇬🇭","Anwar El Ghazi":"🇳🇱","Armando Broja":"🇦🇱","Billy Gilmour":"🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Bobby De Cordova-Reid":"🇯🇲","Brandon Williams":"🏴","Bruno Ecuele Manga":"🇬🇦","Bruno Martins Indi":"🇳🇱",
  "Callum Hudson-Odoi":"🏴","Carlos Baleba":"🇨🇲","Claudio Yacob":"🇦🇷","Dale Stephens":"🏴",
  "Dango Ouattara":"🇧🇫","Dara O'Shea":"🇮🇪","David Brooks":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","DeAndre Yedlin":"🇺🇸",
  "Divock Origi":"🇧🇪","Dusan Tadic":"🇷🇸","Eden Hazard":"🇧🇪","Facundo Buonanotte":"🇦🇷",
  "Gaëtan Bong":"🇨🇲","Gareth Barry":"🏴","Grant Hanley":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Harry Arter":"🇮🇪",
  "Harry Winks":"🏴","Ahmed Hegazi":"🇪🇬","Henrikh Mkhitaryan":"🇦🇲","Jairo Riedewald":"🇳🇱",
  "Jake Livermore":"🏴","Jamal Lewis":"🇬🇧","Jannik Vestergaard":"🇩🇰","Jarrad Branthwaite":"🏴",
  "Jason Puncheon":"🏴","Jayden Bogle":"🏴","João Gomes":"🇧🇷","José Holebas":"🇬🇷",
  "Joško Gvardiol":"🇭🇷","Juan Mata":"🇪🇸","Justin Kluivert":"🇳🇱","Kenny Tete":"🇳🇱",
  "Kieran Gibbs":"🏴","Laurent Koscielny":"🇫🇷","Liam Delap":"🏴","Lloyd Kelly":"🏴",
  "Luke Ayling":"🏴","Martin Kelly":"🏴","Matheus Cunha":"🇧🇷","Max Aarons":"🏴",
  "Maya Yoshida":"🇯🇵","Mesut Özil":"🇩🇪","Milos Kerkez":"🇭🇺","Mohammed Salisu":"🇬🇭",
  "Morgan Rogers":"🏴","Nacho Monreal":"🇪🇸","Neil Etheridge":"🇵🇭","Nicolás Otamendi":"🇦🇷",
  "Nicolas Pépé":"🇨🇮","Ola Aina":"🇳🇬","Oliver McBurnie":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Pablo Zabaleta":"🇦🇷",
  "Lucas Paquetá":"🇧🇷","Patrick Bamford":"🏴","Pau Torres":"🇪🇸","Pedro Obiang":"🇬🇶",
  "Pedro":"🇪🇸","Phil Jagielka":"🏴","Ryan Bennett":"🏴","Ryan Fredericks":"🏴",
  "Ryan Sessegnon":"🏴","Saïd Benrahma":"🇩🇿","Shane Long":"🇮🇪","Tammy Abraham":"🏴",
  "Tim Krul":"🇳🇱","Tim Ream":"🇺🇸","Timo Werner":"🇩🇪","Tosin Adarabioyo":"🏴",
  "Trevoh Chalobah":"🏴","Wes Morgan":"🇯🇲","Wilson Odobert":"🇫🇷","Winston Reid":"🇳🇿",
  "Yasin Ayari":"🇸🇪","Yehor Yarmoliuk":"🇺🇦","Tim Flowers":"🏴",
"Wesley Fofana":"🇫🇷","Đorđe Petrović":"🇷🇸","Tim Flowers":"🏴",
};
